import type { LongTermScanFilters } from "../../types.js";

export function resolveLongTermScanFilters(overrides?: Partial<LongTermScanFilters>): LongTermScanFilters {
  return {
    // Keep enough daily history so weekly/monthly views and 5-year supplementary
    // drawdown checks still have context after aggregation.
    historySessions: 2200,
    recentBaseWindow: 60,
    slopeLookbackSessions: 20,
    higherLowLookbackWindow: 80,
    higherLowPivotSpan: 3,
    majorLowLookbackWindow: 120,
    minimumBaseDays: 15,
    longBaseRewardStartDays: 60,
    longBaseRewardFullDays: 120,
    vShapePenaltyPeakDays: 35,
    minimumHistorySessions: 720,
    minimumTradableTurnover20: 5_000_000_000,
    minimumTradableTurnover60: 4_000_000_000,
    minimumAdHocTradableTurnover60: 15_000_000_000,
    minimumAdHocTurnoverRank: 80,
    minimumAdHocSectorPeerCount: 5,
    minimumAdHocSectorTurnoverRank: 2,
    minimumAdHocLeaderScore: 64,
    minimumDrawdownPct: 25,
    leaderCorrectionMinPct: 20,
    qualityCorrectionMinPct: 25,
    deepValueCorrectionMinPct: 35,
    turnaroundCorrectionMinPct: 40,
    strongDrawdownPct: 35,
    deepDrawdownPct: 45,
    longCycleSupplementDrawdownPct: 40,
    longCycleRecoveryThresholdPct: 5,
    nearHighPenaltyPct: 10,
    overextendedVsMa120Pct: 15,
    farBelowMa240Pct: 25,
    lowBreakPenaltyDays: 12,
    coolingVolumeRatioThreshold: 0.85,
    higherLowQualityBuyFloor: 55,
    accumulateScoreMin: 68,
    buyScoreMin: 78,
    leaderWeight: 0.25,
    correctionWeight: 0.2,
    trendWeight: 0.15,
    liquidityWeight: 0.1,
    stabilizationWeight: 0.15,
    financialWeight: 0.15,
    ...overrides
  };
}
